// End-to-end smoke test. Runs against `vite preview`, which attaches the mock. Exercises
// the shortest path a real user takes:
//   1. The map route loads.
//   2. The illustrative-data banner is present and non-dismissable.
//   3. Opening ?entity=wp-002 (an entity we know has a published finding) renders the
//      panel with coverage ("of") and confidence ("good"/"medium"/"low") visible, and
//      the finding card.
//   4. Zero browser console errors across the test.
//
// IDs are stable because the fixture generator is seeded; see fixtures/generate.ts.

import { test, expect } from '@playwright/test';

const ENTITY_WITH_PUBLISHED = 'wp-002';

// Errors we tolerate: the Protomaps basemap files (/basemap/*) are gitignored and only
// generated by `npm run basemap` with internet (Step 3). A fresh clone running the smoke
// test will see MapLibre errors when it tries to fetch the missing sprite/pmtiles. These
// are environment-setup noise, not app bugs. All other console errors still fail the test.
// We also drop any "Failed to load resource … 404" that resulted from a /basemap/ request,
// because Chromium's generic 404 message does not include the URL.
const BASEMAP_SETUP_NOISE = [/\/basemap\//, /Wrong magic number for PMTiles archive/, /AJAXError/i];

test('smoke: banner, panel scores, published finding, zero console errors', async ({ page }) => {
  const consoleErrors: string[] = [];
  const basemap404Count = { n: 0 };

  page.on('response', (resp) => {
    if (resp.status() === 404 && resp.url().includes('/basemap/')) {
      basemap404Count.n += 1;
    }
  });

  const push = (text: string) => {
    if (BASEMAP_SETUP_NOISE.some((re) => re.test(text))) return;
    // Each basemap 404 generates one generic "Failed to load resource" console error with
    // no URL in the text; consume them in order.
    if (text.includes('Failed to load resource') && basemap404Count.n > 0) {
      basemap404Count.n -= 1;
      return;
    }
    consoleErrors.push(text);
  };
  page.on('console', (msg) => {
    if (msg.type() === 'error') push(msg.text());
  });
  page.on('pageerror', (err) => push(err.message));

  await page.goto('/');

  // Illustrative-data banner (Step 5).
  const banner = page.getByText(/Prototype .+ illustrative data, not real measurements/);
  await expect(banner).toBeVisible();

  // There is no dismiss button inside the banner.
  const bannerContainer = page.locator('[role="status"]').first();
  await expect(bannerContainer.locator('button')).toHaveCount(0);

  // Open the panel by URL (click simulation on a map canvas is fragile headless).
  await page.goto(`/?entity=${ENTITY_WITH_PUBLISHED}`);

  const panel = page.getByRole('complementary', { name: /passport/i });
  await expect(panel).toBeVisible();

  // The entity name appears. Our fixture names water points
  // "Water point NNN (Ward)".
  await expect(panel.getByText(/Water point 002/i)).toBeVisible();

  // Coverage is shown as "X of Y" under every variable row.
  await expect(panel.getByText(/\d+ of \d+/).first()).toBeVisible();

  // Confidence word appears at least once ("low", "medium", or "good").
  await expect(panel.getByText(/confidence (low|medium|good)/i).first()).toBeVisible();

  // Published finding card is present.
  const findings = page.getByRole('region', { name: /findings/i });
  await expect(findings).toBeVisible();
  await expect(
    findings.getByText(/Observed status differs from the recorded status/i)
  ).toBeVisible();

  // No "Not visible" banner for a Viewer (default role).
  await expect(page.getByText(/Not visible to other users/i)).not.toBeVisible();

  // Zero console errors.
  expect(consoleErrors, consoleErrors.join('\n')).toEqual([]);
});
