/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Who is signed in and which screens exist for them (S7, S1 header).
         * @description The read-back after POST /api/login. Session cookie only — a machine holding an X-Api-Key gets 401, because it has no screens to choose between (work pack A-10).
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the full scored entity for the panel (S2). */
        get: operations["getEntityById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            title: string;
            status: number;
            detail?: string;
        };
        /** @description Identity and capability only. PII-tagged columns — the email address above all — are left out (NFR-06), and nothing here reveals what is in the review queue (DEC-08, A-19). */
        CurrentUser: {
            /** @description Greeting for the header's user affordance (S1) and the S7 sign-in confirmation. */
            name: string;
            /**
             * @description The role the server is treating the session as, spelled exactly as app/Auth/Role.php stores it, so the client never guesses the string. `api_client` never appears here: machines authenticate with X-Api-Key and this endpoint takes a session only.
             * @enum {string}
             */
            role: "viewer" | "analyst" | "admin";
            /** @description True for analyst and admin — the same check the API applies to GET /flags. The client renders the review screens only when it is true, so the role-to-capability rule lives on the server (A-19). A capability, never a count: a number would tell a viewer that held findings exist (DEC-08). */
            can_review_findings: boolean;
        };
        EntityDetail: {
            id: string;
            /** @enum {string} */
            entity_type: "water_point" | "road_segment" | "ward";
            /** @enum {string} */
            module: "water" | "roads" | "land";
            name: string;
            ward: string;
            /**
             * @description From the V1 1.1 unmeasured gate (Bible §6.3). `provisional` means the entity's activity gate could not be measured; variable scores are kept but confidence is halved (Bible §6.1 A6). `cannot_assess` means no variable score is reportable.
             * @enum {string}
             */
            gate_status: "measured" | "provisional" | "cannot_assess";
            /**
             * Format: date-time
             * @description Most recent observation across all sub-variables.
             */
            last_observed_at: string | null;
            /**
             * Format: date-time
             * @description When the rollup last ran for this entity.
             */
            last_computed_at: string;
            /** @description Always the five variables, in fixed order V1…V5. */
            variables: components["schemas"]["VariableScore"][];
            sub_variables: components["schemas"]["SubVariableScore"][];
            /** @description Published findings only when returned to a Viewer. Analysts see held and explanation_checked findings here too; the API applies the role filter (DEC-08, A-19). */
            findings: components["schemas"]["FindingSummary"][];
            /** @description Static attribution block for NFR-09. */
            attribution: string;
        };
        VariableScore: {
            /** @enum {string} */
            variable: "V1" | "V2" | "V3" | "V4" | "V5";
            /** @description Display name from docs/CONTEXT.md (DEC-20). */
            name: string;
            /** @description Null when status is 'cannot_assess'. */
            score: number | null;
            /** @description Measured contributors / total contributors for this variable. */
            coverage: number;
            /** @description Rollup confidence after any provisional downweighting. */
            confidence: number;
            /** @enum {string} */
            status: "measured" | "partly_verified" | "cannot_assess";
            /** @enum {string} */
            gate_status: "measured" | "provisional" | "cannot_assess";
            measured_count: number;
            total_count: number;
            /** Format: date-time */
            computed_at: string;
        };
        SubVariableScore: {
            /** @description Internal ID like '1.1', '2.4'. Shown only to analysts/admins on hover. */
            sub_variable: string;
            /** @enum {string} */
            variable: "V1" | "V2" | "V3" | "V4" | "V5";
            /** @description Plain-language label from CONTEXT.md. */
            label: string;
            value: number | null;
            unit: string | null;
            /** @description Null when the sub-variable was not measured. */
            score: number | null;
            confidence: number | null;
            /** @enum {string} */
            status: "measured" | "null_not_measured" | "null_area_only" | "null_not_applicable";
            /** @description Present (and required) whenever status starts with 'null_'. */
            null_reason?: string | null;
            /** Format: date-time */
            observed_at: string | null;
            sources: components["schemas"]["Source"][];
        };
        Source: {
            name: string;
            /** @enum {string} */
            kind: "register" | "observation" | "satellite" | "open_data" | "community";
            /** Format: date */
            date: string;
        };
        FindingSummary: {
            id: string;
            /** @description Which sub-variable raised the finding (2.1, 2.2, 2.4). */
            sub_variable: string;
            /**
             * @description Lifecycle per Bible §6.5 and CONTEXT.md § 4. `contested` means a published finding has been challenged by someone (the subject, a reviewer, or an analyst). Still visible to viewers; the UI shows the challenge copy. `held` and `explanation_checked` and `dismissed` are analyst-only; the API filters them out server-side by the session's role (A-19, DEC-08).
             * @enum {string}
             */
            state: "held" | "explanation_checked" | "published" | "contested" | "dismissed" | "resolved";
            /** @enum {string} */
            severity: "low" | "medium" | "high";
            /** Format: date-time */
            detected_at: string;
            record_says: string;
            we_observe: string;
            /** @description One line, describing the gap. Never a cause, intent or person (PRD §10). */
            gap_summary: string;
            /** Format: date-time */
            published_at: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in user's identity and capability. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            /** @description Nobody is signed in; the sign-in screen (S7) renders on this. Laravel's body is `{"message": "Unauthenticated."}`, which is not the Problem shape below — the generated spec (A-06) reconciles the error contract across every endpoint. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    getEntityById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID (UUIDv7 in production; readable slug in fixtures). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The entity, its variable scores and its sub-variable rows. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDetail"];
                };
            };
            /** @description No entity with that ID, or the entity is retired and the caller is a Viewer. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
